name: Update on server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Update
    runs-on: [ self-hosted ]
    environment: Production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ExXTreMe315/password-generator
          path: production
          ref: main
      - name: copy files
        run: |
          cp -r ./production/src/* /var/www/passwordGenerator
