name: Update on server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Update
    runs-on: [ self-hosted ]
    environment: Production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ExXTreMe315/password-generator
          path: production
          ref: main
      - name: PWD
        run: |
          pwd
      - name: copy files
        run: |
          cp ./password-generator/password-generator/production/index.html /var/www/passwordGenerator
          cp ./password-generator/password-generator/production/script.js /var/www/passwordGenerator
          cp ./password-generator/password-generator/production/style.css /var/www/passwordGenerator
